json.id resource.id
json.name resource.name
json.filter_type resource.filter_type
json.query resource.query
json.shared resource.shared
json.user_id resource.user_id
json.owner_name resource.user&.available_name
json.created_at resource.created_at
json.updated_at resource.updated_at
