#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# lint js and vue files
npx --no-install lint-staged

# lint only staged ruby files
git diff --name-only --cached | xargs -r ls -1 2>/dev/null | grep '\.rb$' | xargs -r bundle exec rubocop --force-exclusion -a

# stage rubocop changes to files
git diff --name-only --cached | xargs -r git add
